# Generated by Django 5.2.12 on 2026-04-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom interne de la promotion. Ex : 'Soldes été 2026 -30%'.", max_length=150)),
                ('description', models.TextField(blank=True, help_text='Description affichée au client en boutique ou sur le ticket.')),
                ('type', models.CharField(choices=[('pourcentage', 'Pourcentage (ex. -20%)'), ('valeur_fixe', 'Valeur fixe (ex. -5 000 FCFA)'), ('offre_panier', 'Offre panier (ex. 2 achetés = 1 offert)')], help_text='Nature de la remise.', max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, help_text='Valeur de la remise : 20.00 pour 20% (si type=pourcentage), ou 5000.00 FCFA (si type=valeur_fixe).', max_digits=10)),
                ('portee', models.CharField(choices=[('article', 'Article spécifique'), ('categorie', 'Catégorie entière'), ('panier', 'Panier global'), ('client', 'Segment client spécifique')], help_text="Sur quoi s'applique la promotion.", max_length=20)),
                ('date_debut', models.DateTimeField(help_text='Début de validité. La promotion est inactive avant cette date.')),
                ('date_fin', models.DateTimeField(blank=True, help_text='Fin de validité. Null = promotion permanente sans date de fin.', null=True)),
                ('montant_min_panier', models.DecimalField(blank=True, decimal_places=2, help_text='Panier minimum requis pour déclencher la promotion. Null = pas de minimum.', max_digits=12, null=True)),
                ('usages_max', models.IntegerField(blank=True, help_text="Nombre maximum total d'utilisations. Null = illimité.", null=True)),
                ('usages_actuels', models.IntegerField(default=0, help_text="Compteur d'utilisations. Incrémenté atomiquement via F() expression pour éviter les race conditions.")),
                ('actif', models.BooleanField(default=True, help_text="Activation manuelle. Permet de préparer des promotions à l'avance.")),
                ('article_cible', models.ForeignKey(blank=True, help_text="Article ciblé si portee='article'. Null sinon.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalogue.article')),
                ('categorie_cible', models.ForeignKey(blank=True, help_text="Catégorie ciblée si portee='categorie'. Null sinon.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='catalogue.categorie')),
                ('magasin', models.ForeignKey(help_text='Magasin pour lequel cette promotion est valable.', on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='administration.magasin')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['magasin', 'actif', 'date_debut', 'date_fin'], name='promotions__magasin_da6b74_idx')],
            },
        ),
    ]
