# Generated by Django 5.2.12 on 2026-04-16 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom commercial affiché sur les tickets et factures. Ex : 'Boutique Fatou Mode'.", max_length=150)),
                ('adresse', models.TextField(help_text='Adresse complète imprimée sur les documents commerciaux.')),
                ('telephone', models.CharField(blank=True, help_text='Téléphone de contact affiché sur les tickets.', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Email de contact du magasin.', max_length=254)),
                ('logo', models.ImageField(blank=True, help_text="Logo affiché sur les tickets imprimés et dans l'interface Next.js.", null=True, upload_to='magasins/logos/')),
                ('devise', models.CharField(default='XOF', help_text="Code ISO de la devise locale. XOF = FCFA (Afrique de l'Ouest), EUR, MAD... Utilisé pour formater tous les montants affichés.", max_length=10)),
                ('taux_tva_defaut', models.DecimalField(decimal_places=2, default=18.0, help_text='Taux de TVA par défaut (en %) appliqué aux nouveaux articles créés dans ce magasin. Peut être surchargé article par article.', max_digits=5)),
                ('actif', models.BooleanField(default=True, help_text="Si False, la boutique n'est plus accessible dans l'interface.")),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text="Nom du rôle. Ex : 'Administrateur', 'Vendeur'.", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description des droits accordés par ce rôle, affichée dans l'admin.")),
                ('permissions', models.JSONField(default=dict, help_text="Dictionnaire JSON des permissions accordées. Exemple : {'vente.create': true, 'config.edit': false}. Vérifié par une permission class DRF custom.")),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nom', models.CharField(help_text="Nom de famille, affiché dans l'interface et les rapports.", max_length=100)),
                ('prenom', models.CharField(help_text='Prénom.', max_length=100)),
                ('email', models.EmailField(help_text='Email professionnel. Utilisé pour les notifications système et la réinitialisation de mot de passe.', max_length=254, unique=True)),
                ('actif', models.BooleanField(default=True, help_text="Compte désactivé = impossible de se connecter. Préférer la désactivation à la suppression pour conserver l'historique.")),
                ('code_pin', models.CharField(blank=True, help_text='Code PIN à 4-6 chiffres pour déverrouillage rapide de la caisse. Hashé en base avec make_password().', max_length=128)),
                ('deux_facteurs_secret', models.CharField(blank=True, help_text='Secret TOTP utilisé pour générer les codes 2FA.', max_length=64)),
                ('deux_facteurs_actif', models.BooleanField(default=False, help_text='Indique si le 2FA est activé pour cet utilisateur.')),
                ('deux_facteurs_methode', models.CharField(choices=[('totp', 'Application'), ('sms', 'SMS'), ('email', 'Email')], default='totp', help_text='Méthode choisie pour la double authentification.', max_length=20)),
                ('codes_secours', models.JSONField(blank=True, default=list, help_text='Codes de secours utilisables une seule fois lorsque le 2FA est activé.')),
                ('derniere_connexion', models.DateTimeField(blank=True, help_text='Date de dernière connexion validée.', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du compte utilisateur.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('magasin', models.ForeignKey(blank=True, help_text='Magasin de rattachement principal. Null pour les administrateurs ayant accès à toutes les boutiques.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='administration.magasin')),
                ('role', models.ForeignKey(blank=True, help_text="Rôle déterminant les permissions (admin, vendeur). PROTECT : impossible de supprimer un rôle tant qu'un utilisateur le porte.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='administration.role')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(help_text="Clé unique en snake_case avec namespace. Ex : 'fidelite.taux_points_par_fcfa', 'ticket.texte_pied', 'avoir.duree_validite_jours'.", max_length=200, unique=True)),
                ('valeur', models.TextField(help_text="Valeur stockée sous forme de texte. La conversion vers le bon type (int, bool, JSON) est faite par ParametreService selon le champ 'type'.")),
                ('type', models.CharField(choices=[('string', 'Texte'), ('integer', 'Entier'), ('boolean', 'Booléen (true/false)'), ('decimal', 'Décimal'), ('json', 'JSON')], default='string', help_text='Type de la valeur. Utilisé par ParametreService pour le cast automatique.', max_length=20)),
                ('description', models.TextField(blank=True, help_text="Explication de l'effet de ce paramètre, affichée dans l'interface d'administration pour aider le gérant à comprendre ce qu'il modifie.")),
                ('magasin', models.ForeignKey(blank=True, help_text="Si renseigné, ce paramètre s'applique uniquement à ce magasin. Si null, c'est un paramètre global commun à toutes les boutiques.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='administration.magasin')),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['cle'],
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Verbe de l'opération. Ex : 'CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'VALIDER_VENTE', 'CLOTURER_CAISSE'.", max_length=100)),
                ('entite', models.CharField(help_text="Nom de la classe Django concernée. Ex : 'Vente', 'Article', 'MouvementStock'. Permet de filtrer par type d'objet.", max_length=100)),
                ('entite_id', models.UUIDField(blank=True, help_text="UUID de l'objet modifié. Combiné avec 'entite' pour retrouver l'enregistrement source. Pas de vraie FK pour éviter les contraintes de suppression.", null=True)),
                ('ancienne_valeur', models.JSONField(blank=True, help_text="Snapshot JSON de l'état de l'objet AVANT la modification. Null pour un CREATE.", null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, help_text="Snapshot JSON de l'état de l'objet APRÈS la modification. Null pour un DELETE.", null=True)),
                ('date_heure', models.DateTimeField(auto_now_add=True, help_text='Horodatage côté serveur. Généré automatiquement, non modifiable.')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, help_text="IP du poste ayant effectué l'action. Utile pour les audits de sécurité.", null=True)),
                ('utilisateur', models.ForeignKey(help_text="Utilisateur ayant déclenché l'action.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date_heure'],
                'indexes': [models.Index(fields=['entite', 'entite_id'], name='administrat_entite_587321_idx'), models.Index(fields=['utilisateur', 'date_heure'], name='administrat_utilisa_22db95_idx')],
            },
        ),
    ]
