# Generated by Django 5.2.12 on 2026-04-16 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('catalogue', '0002_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text="Nom affiché du poste. Ex : 'Caisse principale', 'Caisse rapide'.", max_length=100)),
                ('emplacement', models.CharField(blank=True, help_text="Description physique de l'emplacement dans le magasin.", max_length=150)),
                ('actif', models.BooleanField(default=True, help_text='Si False, la caisse ne peut plus être ouverte. Permet de désactiver un poste.')),
                ('magasin', models.ForeignKey(help_text='Magasin auquel appartient cette caisse.', on_delete=django.db.models.deletion.PROTECT, related_name='caisses', to='administration.magasin')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['magasin', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(help_text="Nombre d'unités vendues. Validation : min=1, ne peut pas dépasser le stock disponible.")),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, help_text="Prix d'une unité HT au moment de la vente. Figé pour conserver l'historique.", max_digits=12)),
                ('prix_unitaire_ttc', models.DecimalField(decimal_places=2, help_text="Prix d'une unité TTC au moment de la vente. Affiché au client.", max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, help_text="Taux de TVA applicable à cet article au moment de la vente. Figé pour l'historique comptable.", max_digits=5)),
                ('remise_ligne', models.DecimalField(decimal_places=2, default=0, help_text='Remise en valeur absolue accordée sur cette ligne (promotion, solde). 0 si aucune remise.', max_digits=12)),
                ('total_ligne_ttc', models.DecimalField(decimal_places=2, default=0, help_text='Montant total TTC de la ligne après remise. = (prix_unitaire_ttc × quantite) - remise_ligne. Calculé automatiquement dans save().', max_digits=12)),
                ('declinaison', models.ForeignKey(help_text="Déclinaison précise de l'article vendu (taille + coloris). PROTECT : on conserve l'historique même si la déclinaison est désactivée.", on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='catalogue.declinaison')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
                'ordering': ['vente', 'declinaison'],
            },
        ),
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retour', models.DateTimeField(auto_now_add=True, help_text='Horodatage du retour enregistré côté serveur.')),
                ('motif', models.TextField(help_text='Raison du retour saisie par le vendeur : défaut produit, taille incorrecte, etc.')),
                ('type_retour', models.CharField(choices=[('remboursement', 'Remboursement (espèces ou carte)'), ('echange', 'Échange (nouvelle vente créée)'), ('avoir', 'Avoir (crédit sur compte client)')], help_text='Nature du retour : remboursement, échange ou avoir.', max_length=20)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, help_text='Montant restitué au client. 0 si type = échange ou avoir.', max_digits=12)),
                ('statut', models.CharField(choices=[('valide', 'Validé'), ('annule', 'Annulé')], default='valide', help_text='État du retour.', max_length=20)),
                ('avoir', models.OneToOneField(blank=True, help_text="Avoir généré si type_retour='avoir'. Null pour les remboursements directs.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retour_source', to='clients.avoir')),
                ('vendeur', models.ForeignKey(help_text='Vendeur ayant traité le retour, pour traçabilité et responsabilité.', on_delete=django.db.models.deletion.PROTECT, related_name='retours_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retour',
                'verbose_name_plural': 'Retours',
                'ordering': ['-date_retour'],
            },
        ),
        migrations.CreateModel(
            name='LigneRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_retournee', models.PositiveIntegerField(help_text="Nombre d'unités retournées. Validation : quantite_retournee <= ligne_vente_originale.quantite.")),
                ('montant_rembourse_ligne', models.DecimalField(decimal_places=2, default=0, help_text='Montant remboursé pour cette ligne = quantite_retournee × prix_unitaire_ttc.', max_digits=12)),
                ('ligne_vente_originale', models.ForeignKey(help_text="Ligne de vente originale concernée par ce retour. Permet de vérifier qu'on ne retourne pas plus que ce qui a été acheté.", on_delete=django.db.models.deletion.PROTECT, related_name='lignes_retour', to='ventes.lignevente')),
                ('retour', models.ForeignKey(help_text='Retour auquel appartient cette ligne.', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.retour')),
            ],
            options={
                'verbose_name': 'Ligne de retour',
                'verbose_name_plural': 'Lignes de retour',
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(help_text="Moment d'ouverture de la session, enregistré côté serveur.")),
                ('date_fermeture', models.DateTimeField(blank=True, help_text='Moment de fermeture. Null si la session est encore ouverte.', null=True)),
                ('fond_caisse', models.DecimalField(decimal_places=2, default=0, help_text="Montant en espèces présent dans le tiroir à l'ouverture, déclaré manuellement.", max_digits=12)),
                ('total_encaisse', models.DecimalField(decimal_places=2, default=0, help_text='Cumul de toutes les ventes encaissées pendant la session. Mis à jour en temps réel.', max_digits=12)),
                ('total_especes', models.DecimalField(decimal_places=2, default=0, help_text='Part du total encaissé en espèces. Permet le contrôle du tiroir à la fermeture.', max_digits=12)),
                ('total_carte', models.DecimalField(decimal_places=2, default=0, help_text='Part du total encaissé par carte bancaire et mobile money.', max_digits=12)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', help_text="Une seule session 'ouverte' par caisse à la fois.", max_length=20)),
                ('caisse', models.ForeignKey(help_text='Caisse physique concernée.', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='ventes.caisse')),
                ('vendeur', models.ForeignKey(help_text='Utilisateur ayant ouvert la session.', on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(help_text="Numéro de bon lisible. Ex : 'VTE-2026-00042'. Généré séquentiellement par le backend. Affiché sur le ticket de caisse.", max_length=50, unique=True)),
                ('date_heure', models.DateTimeField(auto_now_add=True, help_text='Date et heure exactes de création de la vente, générées côté serveur. Ne jamais laisser le client (frontend) fournir cette valeur.')),
                ('statut', models.CharField(choices=[('validee', 'Validée'), ('retournee', 'Retournée')], default='validee', help_text="État de la vente. 'validee' à la création, 'retournee' après traitement d'un retour.", max_length=20)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, help_text='Somme des montants HT des lignes de vente, avant TVA et remise globale.', max_digits=12)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, help_text='Montant de TVA collecté. Nécessaire pour les exports comptables.', max_digits=12)),
                ('montant_remise', models.DecimalField(decimal_places=2, default=0, help_text='Montant total de remise accordée (promotions globales, remise manuelle vendeur).', max_digits=12)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, help_text='Montant total TTC payé par le client. Affiché en grand sur le ticket.', max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, help_text='Somme effectivement reçue, tous modes de paiement confondus. Peut dépasser total_ttc (excès rendu en monnaie).', max_digits=12)),
                ('montant_rendu', models.DecimalField(decimal_places=2, default=0, help_text="Monnaie rendue au client lors d'un paiement en espèces. = montant_paye - total_ttc si positif.", max_digits=12)),
                ('client', models.ForeignKey(blank=True, help_text='Client associé à cette vente. Null = vente anonyme. Si renseigné, les points de fidélité sont crédités automatiquement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='clients.client')),
                ('magasin', models.ForeignKey(help_text='Magasin où la vente a été effectuée.', on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='administration.magasin')),
                ('session_caisse', models.ForeignKey(help_text='Session de caisse durant laquelle la vente a été réalisée. Permet la réconciliation de caisse quotidienne.', on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='ventes.sessioncaisse')),
                ('vendeur', models.ForeignKey(help_text='Vendeur ayant réalisé la vente. Permet le suivi des performances par vendeur.', on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.AddField(
            model_name='retour',
            name='vente_originale',
            field=models.ForeignKey(help_text="Vente d'origine concernée par le retour. Permet la traçabilité complète.", on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='ventes.vente'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money (Wave, Orange Money...)'), ('avoir', 'Avoir client'), ('bon_cadeau', 'Bon cadeau'), ('cheque', 'Chèque')], help_text='Mode de paiement utilisé.', max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, help_text="Montant encaissé via ce mode. La somme de tous les paiements d'une vente doit correspondre au total TTC.", max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Numéro de transaction externe : numéro de chèque, référence carte, code mobile money. Laissé vide pour les espèces.', max_length=100)),
                ('date_heure', models.DateTimeField(auto_now_add=True, help_text='Horodatage du paiement côté serveur.')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('rejete', 'Rejeté (carte refusée)'), ('en_attente', 'En attente (chèque à encaisser)')], default='valide', help_text='État du paiement. Permet le suivi des paiements différés (chèques).', max_length=20)),
                ('avoir', models.ForeignKey(blank=True, help_text="Avoir utilisé si mode_paiement='avoir'. Null sinon.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilisations', to='clients.avoir')),
                ('session_caisse', models.ForeignKey(help_text='Caisse sur laquelle le paiement a été enregistré. Permet la réconciliation quotidienne.', on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='ventes.sessioncaisse')),
                ('vente', models.ForeignKey(help_text='Vente associée à ce règlement.', on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.AddField(
            model_name='lignevente',
            name='vente',
            field=models.ForeignKey(help_text='Vente à laquelle appartient cette ligne. CASCADE : supprimée avec la vente.', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['magasin', 'date_heure'], name='ventes_vent_magasin_76854f_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['vendeur', 'date_heure'], name='ventes_vent_vendeur_bfc17f_idx'),
        ),
        migrations.AddIndex(
            model_name='vente',
            index=models.Index(fields=['client'], name='ventes_vent_client__a61544_idx'),
        ),
    ]
