# Generated by Django 5.2.12 on 2026-04-16 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de famille du client.', max_length=100)),
                ('prenom', models.CharField(help_text='Prénom du client.', max_length=100)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone principal. Utilisé comme identifiant rapide en caisse. Format international recommandé (+226 XX XX XX XX). unique=True avec null=True : plusieurs clients peuvent ne pas avoir de téléphone.', max_length=30, null=True, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Adresse email. Utilisée pour les notifications et le programme fidélité digital.', max_length=254, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, help_text='Adresse postale complète. Optionnelle.')),
                ('date_naissance', models.DateField(blank=True, help_text="Utilisée pour envoyer un SMS/email d'anniversaire avec une offre.", null=True)),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('non_precise', 'Non précisé')], default='non_precise', help_text='Permet la segmentation marketing par genre.', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, help_text='Date de création du compte client.')),
                ('points_fidelite', models.IntegerField(default=0, help_text="Solde actuel de points de fidélité. Incrémenté à chaque achat validé, décrémenté à l'utilisation.")),
                ('niveau_fidelite', models.CharField(choices=[('bronze', 'Bronze'), ('argent', 'Argent'), ('or', 'Or'), ('platine', 'Platine')], default='bronze', help_text='Niveau fidélité : bronze, argent, or, platine. Recalculé automatiquement selon le montant total dépensé sur 12 mois glissants.', max_length=20)),
                ('numero_carte_fidelite', models.CharField(blank=True, help_text='Numéro de carte fidélité physique ou virtuelle. Scannable en caisse via code-barres.', max_length=50, null=True, unique=True)),
                ('actif', models.BooleanField(default=True, help_text="Soft delete. Un client inactif n'apparaît plus dans les recherches mais son historique des achats est conservé.")),
                ('notes', models.TextField(blank=True, help_text='Notes internes du vendeur sur le client : préférences, tailles habituelles.')),
                ('magasin', models.ForeignKey(help_text='Magasin où le client a été enregistré.', on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='administration.magasin')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro lisible de l'avoir. Ex : 'AV-2026-0042'. Imprimé sur le reçu de retour.", max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, help_text="Valeur totale initiale de l'avoir.", max_digits=12)),
                ('montant_utilise', models.DecimalField(decimal_places=2, default=0, help_text='Part déjà consommée en caisse. Incrémenté à chaque utilisation partielle.', max_digits=12)),
                ('date_expiration', models.DateField(help_text="Date limite d'utilisation. Au-delà, l'avoir passe en statut 'expire'.")),
                ('statut', models.CharField(choices=[('actif', 'Actif (utilisable)'), ('utilise', 'Utilisé (solde = 0)'), ('expire', 'Expiré (date dépassée)')], default='actif', help_text="État de l'avoir.", max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date de création de l'avoir.")),
                ('client', models.ForeignKey(help_text="Client bénéficiaire de l'avoir.", on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='clients.client')),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['telephone'], name='clients_cli_telepho_8c69d9_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['numero_carte_fidelite'], name='clients_cli_numero__d188cc_idx'),
        ),
    ]
