# Generated by Django 5.2.12 on 2026-04-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text="Code article interne lisible. Ex : 'ART-2026-001'. Unique dans tout le catalogue. Généré séquentiellement par le backend.", max_length=100, unique=True)),
                ('designation', models.CharField(help_text='Nom commercial affiché en boutique et sur le ticket de caisse.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée : matière, entretien, conseils de port.')),
                ('prix_achat_ht', models.DecimalField(decimal_places=2, default=0, help_text="Prix d'achat hors taxes auprès du fournisseur. CONFIDENTIEL — ne jamais transmettre au frontend client.", max_digits=12)),
                ('prix_vente_ttc', models.DecimalField(decimal_places=2, help_text='Prix de vente public TTC. Peut être surchargé au niveau de la déclinaison (prix_vente_specifique).', max_digits=12)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, help_text='Taux de TVA applicable en %. Ex : 18.00. Dépend de la réglementation locale.', max_digits=5)),
                ('genre', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('enfant', 'Enfant'), ('mixte', 'Mixte')], default='mixte', help_text='Genre cible. Utilisé pour le filtrage dans le catalogue.', max_length=20)),
                ('actif', models.BooleanField(default=True, help_text="Si False, l'article n'apparaît plus dans le catalogue ni en caisse (soft delete). L'historique des ventes est conservé.")),
                ('photo', models.ImageField(blank=True, help_text="Photo principale. URL servie par l'API REST et affichée par Next.js.", null=True, upload_to='articles/photos/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout au catalogue, générée automatiquement.")),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text="Nom affiché de la catégorie. Ex : 'Robes', 'Chaussures', 'Accessoires'.", max_length=150)),
                ('description', models.TextField(blank=True, help_text='Description optionnelle affichée en en-tête de la page de catégorie.')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le menu. Triées par ordre croissant.")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Intitulé de la collection. Ex : 'Printemps-Été 2026'.", max_length=150)),
                ('saison', models.CharField(choices=[('PE', 'Printemps-Été'), ('AH', 'Automne-Hiver'), ('toute_saison', 'Toute saison')], help_text="Saison commerciale. Combinée avec 'annee' pour l'identification.", max_length=20)),
                ('annee', models.PositiveIntegerField(help_text='Année de la collection. Ex : 2026.')),
                ('date_debut', models.DateField(help_text='Date de mise en vente officielle de la collection.')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin de commercialisation. Null = collection permanente sans fin.', null=True)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-annee', 'saison'],
            },
        ),
        migrations.CreateModel(
            name='Declinaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(help_text="Taille textuelle : XS, S, M, L, XL, XXL, ou numérique pour chaussures (38, 39...). Libre pour s'adapter à tous les secteurs.", max_length=20)),
                ('coloris', models.CharField(help_text="Nom de la couleur. Ex : 'Noir', 'Blanc', 'Bleu marine'. Affiché dans la grille.", max_length=100)),
                ('code_barres', models.CharField(help_text="Code EAN13 scannable par le lecteur de caisse. Généré automatiquement dans save() si laissé vide, ou saisi manuellement si l'article vient avec son propre code-barres fournisseur.", max_length=50, unique=True)),
                ('stock_actuel', models.IntegerField(default=0, help_text='Quantité physiquement disponible en boutique. Décrémenté à chaque vente validée, incrémenté à chaque réception fournisseur. NE JAMAIS modifier directement — passer par un MouvementStock.')),
                ('stock_minimum', models.IntegerField(default=0, help_text="Seuil d'alerte de réapprovisionnement. Si stock_actuel <= stock_minimum, une alerte est générée.")),
                ('stock_maximum', models.IntegerField(blank=True, help_text='Stock cible maximal. Permet de calculer la quantité optimale à commander : stock_maximum - stock_actuel.', null=True)),
                ('prix_vente_specifique', models.DecimalField(blank=True, decimal_places=2, help_text="Prix spécifique pour cette déclinaison, remplaçant le prix de l'article parent. Null = utiliser article.prix_vente_ttc.", max_digits=12, null=True)),
                ('actif', models.BooleanField(default=True, help_text="Déclinaison désactivée = ne peut plus être vendue. Permet de retirer une taille épuisée définitivement sans supprimer l'historique.")),
            ],
            options={
                'verbose_name': 'Déclinaison',
                'verbose_name_plural': 'Déclinaisons',
                'ordering': ['article', 'taille', 'coloris'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateTimeField(help_text="Date et heure de réalisation de l'inventaire.")),
                ('type', models.CharField(choices=[('complet', 'Complet (tout le stock)'), ('partiel', 'Partiel (sélection de rayons ou catégories)')], help_text="Portée de l'inventaire : complet ou partiel.", max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_cours', help_text="État de l'inventaire. Un seul inventaire 'en_cours' autorisé par magasin à la fois.", max_length=20)),
                ('observation', models.TextField(blank=True, help_text="Notes libres sur les conditions de l'inventaire : zone concernée, anomalies constatées, conditions particulières.")),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.IntegerField(help_text="Stock enregistré en base au moment du début de l'inventaire.")),
                ('quantite_comptee', models.IntegerField(help_text='Quantité physiquement comptée sur le terrain par le responsable.')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la marque. Unique pour éviter les doublons.', max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo affiché dans le catalogue et les fiches produits.', null=True, upload_to='marques/logos/')),
                ('description', models.TextField(blank=True, help_text='Présentation de la marque, affichée sur sa page dédiée.')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entree', 'Entrée (réception fournisseur)'), ('sortie', 'Sortie (vente)'), ('ajustement_positif', 'Ajustement positif (inventaire)'), ('ajustement_negatif', 'Ajustement négatif (casse/vol)'), ('retour_client', 'Retour client remis en stock')], help_text='Nature du mouvement. La quantite est toujours positive ; le type indique le sens.', max_length=30)),
                ('quantite', models.PositiveIntegerField(help_text="Nombre d'unités déplacées. Toujours positif.")),
                ('quantite_avant', models.IntegerField(help_text="Stock AVANT le mouvement. Capturé automatiquement pour permettre l'audit et la reconstruction de l'historique.")),
                ('quantite_apres', models.IntegerField(help_text='Stock APRÈS le mouvement. = quantite_avant + quantite (entrée/ajustement_positif/retour_client) ou quantite_avant - quantite (sortie/ajustement_negatif).')),
                ('motif', models.CharField(blank=True, help_text="Raison de l'ajustement manuel : 'casse', 'vol', 'erreur d'inventaire'. Vide pour les mouvements automatiques (vente, réception).", max_length=255)),
                ('date_heure', models.DateTimeField(auto_now_add=True, help_text="Horodatage côté serveur. Indispensable pour reconstituer l'historique dans l'ordre.")),
                ('source', models.JSONField(blank=True, help_text="Référence vers l'objet à l'origine du mouvement. Ex : {'type': 'vente', 'id': 'uuid-de-la-vente'}. Permet de retrouver la vente ou la commande liée à ce mouvement.", null=True)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_heure'],
            },
        ),
    ]
