# Generated by Django 5.2.12 on 2026-04-16 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('founisseurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text='Fournisseur principal de cet article pour les réapprovisionnements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='founisseurs.fournisseur'),
        ),
        migrations.AddField(
            model_name='article',
            name='magasin',
            field=models.ForeignKey(help_text="Magasin auquel appartient cet article. Permet l'isolation multi-boutiques.", on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='administration.magasin'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='categorie_parent',
            field=models.ForeignKey(blank=True, help_text='Catégorie parente. Null = catégorie racine. Permet la hiérarchie auto-référente. PROTECT : impossible de supprimer si des sous-catégories existent.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sous_categories', to='catalogue.categorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(help_text="Catégorie de l'article (pouvant être hiérarchique). Ex : Vêtements > Femme > Robes.", on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='catalogue.categorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection saisonnière. Null si article permanent au catalogue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='catalogue.collection'),
        ),
        migrations.AddField(
            model_name='declinaison',
            name='article',
            field=models.ForeignKey(help_text="Article parent. related_name='declinaisons' permet article.declinaisons.all() pour récupérer toutes les variantes.", on_delete=django.db.models.deletion.PROTECT, related_name='declinaisons', to='catalogue.article'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='magasin',
            field=models.ForeignKey(help_text="Magasin concerné par l'inventaire.", on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to='administration.magasin'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='utilisateur',
            field=models.ForeignKey(help_text="Responsable de l'inventaire (gestionnaire ou gérant).", on_delete=django.db.models.deletion.PROTECT, related_name='inventaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='declinaison',
            field=models.ForeignKey(help_text='Déclinaison comptée.', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='catalogue.declinaison'),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='inventaire',
            field=models.ForeignKey(help_text="Inventaire auquel appartient cette ligne. CASCADE : supprimé avec l'inventaire.", on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='catalogue.inventaire'),
        ),
        migrations.AddField(
            model_name='article',
            name='marque',
            field=models.ForeignKey(help_text="Marque de l'article. PROTECT : impossible de supprimer une marque utilisée.", on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='catalogue.marque'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='declinaison',
            field=models.ForeignKey(help_text='Déclinaison concernée par ce mouvement de stock.', on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to='catalogue.declinaison'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='utilisateur',
            field=models.ForeignKey(help_text="Utilisateur à l'origine du mouvement. Pour les mouvements automatiques (vente), c'est le vendeur.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='declinaison',
            index=models.Index(fields=['code_barres'], name='catalogue_d_code_ba_2ad016_idx'),
        ),
        migrations.AddIndex(
            model_name='declinaison',
            index=models.Index(fields=['article', 'actif'], name='catalogue_d_article_bf6af3_idx'),
        ),
        migrations.AddConstraint(
            model_name='declinaison',
            constraint=models.UniqueConstraint(fields=('article', 'taille', 'coloris'), name='unique_declinaison_article_taille_coloris'),
        ),
        migrations.AddConstraint(
            model_name='ligneinventaire',
            constraint=models.UniqueConstraint(fields=('inventaire', 'declinaison'), name='unique_ligne_inventaire_declinaison'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['reference'], name='catalogue_a_referen_48d685_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['magasin', 'actif'], name='catalogue_a_magasin_653cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['declinaison', 'date_heure'], name='catalogue_m_declina_bc36b9_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['type', 'date_heure'], name='catalogue_m_type_92deda_idx'),
        ),
    ]
