# Generated by Django 5.2.12 on 2026-04-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declinaison',
            name='article',
            field=models.ForeignKey(help_text="Article parent. related_name='declinaisons' permet article.declinaisons.all() pour récupérer toutes les variantes.", on_delete=django.db.models.deletion.CASCADE, related_name='declinaisons', to='catalogue.article'),
        ),
    ]
