# Generated by Django 5.2.12 on 2026-04-16 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(help_text='Nom légal complet du fournisseur.', max_length=200)),
                ('contact', models.CharField(blank=True, help_text='Nom du contact commercial chez le fournisseur.', max_length=150)),
                ('telephone', models.CharField(blank=True, help_text='Téléphone principal du fournisseur.', max_length=30)),
                ('email', models.EmailField(blank=True, help_text='Email commercial pour les commandes.', max_length=254)),
                ('adresse', models.TextField(blank=True, help_text='Adresse complète du fournisseur.')),
                ('pays', models.CharField(blank=True, help_text='Pays du fournisseur. Utile pour les imports et la gestion des devises.', max_length=100)),
                ('delai_livraison', models.PositiveIntegerField(default=7, help_text='Délai de livraison habituel en jours ouvrés. Utilisé pour calculer la date prévisionnelle de réception.')),
                ('conditions_paiement', models.TextField(blank=True, help_text='Conditions de règlement : virement à 30 jours, paiement à la commande, etc.')),
                ('actif', models.BooleanField(default=True, help_text="Fournisseur désactivé = n'apparaît plus dans les nouveaux bons de commande.")),
                ('notes', models.TextField(blank=True, help_text='Notes internes : qualité des produits, fiabilité des délais, contacts alternatifs.')),
                ('magasin', models.ForeignKey(help_text='Magasin ayant ce fournisseur dans son répertoire.', on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='administration.magasin')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text="Numéro de bon de commande. Ex : 'BC-2026-0018'. Communiqué au fournisseur.", max_length=50, unique=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True, help_text='Date de création du bon de commande.')),
                ('date_livraison_prevue', models.DateField(blank=True, help_text='Date prévisionnelle de livraison, calculée depuis delai_livraison du fournisseur.', null=True)),
                ('date_livraison_effective', models.DateField(blank=True, help_text="Date réelle de la dernière réception. Permet d'évaluer la ponctualité du fournisseur.", null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('partiellement_recue', 'Partiellement reçue'), ('soldee', 'Soldée (tout reçu)'), ('annulee', 'Annulée')], default='en_attente', help_text='État de la commande. Géré automatiquement par le service métier.', max_length=30)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, help_text='Montant total HT de la commande. Recalculé automatiquement depuis la somme des LigneCommande.', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Instructions spéciales au fournisseur : conditionnement, priorité, références.')),
                ('magasin', models.ForeignKey(help_text='Magasin pour lequel cette commande est passée.', on_delete=django.db.models.deletion.PROTECT, related_name='commandes_fournisseur', to='administration.magasin')),
                ('utilisateur', models.ForeignKey(help_text='Utilisateur ayant passé la commande (gestionnaire de stock ou gérant).', on_delete=django.db.models.deletion.PROTECT, related_name='commandes_fournisseur', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(help_text='Fournisseur destinataire de la commande.', on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='founisseurs.fournisseur')),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseurs',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.PositiveIntegerField(help_text="Nombre d'unités commandées au fournisseur.")),
                ('quantite_recue', models.PositiveIntegerField(default=0, help_text="Nombre d'unités effectivement reçues à ce jour. Incrémenté à chaque réception partielle ou totale. Quand quantite_recue == quantite_commandee, la ligne est soldée.")),
                ('prix_achat_unitaire', models.DecimalField(decimal_places=2, help_text="Prix d'achat unitaire HT négocié avec le fournisseur pour cette commande. Figé à la création de la ligne (peut différer du prix_achat_ht habituel de l'article).", max_digits=12)),
                ('total_ligne', models.DecimalField(decimal_places=2, default=0, help_text='Montant total HT de cette ligne = quantite_commandee × prix_achat_unitaire. Calculé automatiquement dans save().', max_digits=12)),
                ('commande', models.ForeignKey(help_text='Commande fournisseur à laquelle appartient cette ligne. CASCADE : supprimée si la commande est supprimée.', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='founisseurs.commandefournisseur')),
                ('declinaison', models.ForeignKey(help_text="Déclinaison précise de l'article commandé (article + taille + coloris). PROTECT : on conserve l'historique des commandes même si la déclinaison est désactivée.", on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='catalogue.declinaison')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'ordering': ['commande', 'declinaison'],
                'constraints': [models.UniqueConstraint(fields=('commande', 'declinaison'), name='unique_ligne_commande_declinaison')],
            },
        ),
    ]
